export const answerAttacks: string[] = [
    "Sua rima é tão fraca, parece um sussurro",
    "Seu flow é tão lento, parece que está em câmera lenta",
    "Suas rimas são tão previsíveis, não causam impacto",
    "Sua métrica está fora de compasso, não tem ritmo",
    "Você se perde nas palavras, parece uma confusão",
    "Suas rimas são rasas, não têm profundidade",
    "Seu vocabulário é limitado, falta criatividade",
    "Suas palavras não têm força, são apenas vazias",
    "Sua cadência é desajeitada, não flui naturalmente",
    "Suas rimas são infantis, falta maturidade",
    "Você tenta rimar, mas parece que falta prática",
    "Suas metáforas são clichês, não surpreendem",
    "Seu punchline é fraco, não tem impacto",
    "Sua rima é tão simples, falta complexidade",
    "Suas palavras não se encaixam, não têm harmonia",
    "Seu estilo é repetitivo, falta originalidade",
    "Suas rimas não têm contundência, são fracas",
    "Você se perde no ritmo, parece um tropeço",
    "Suas palavras são desconexas, falta coesão",
    "Sua rima é tão óbvia, não traz novidade",
    "Seu flow é monótono, falta variação",
    "Suas rimas não têm impacto, passam despercebidas",
    "Você tenta rimar, mas falta fluidez",
    "Suas palavras são vazias, não têm substância",
    "Sua métrica é confusa, falta clareza",
    "Suas rimas não têm poder, são fracas como um sopro",
    "Você se perde no compasso, parece desafinado",
    "Suas palavras não têm emoção, falta paixão",
    "Sua rima é tão previsível, não surpreende ninguém",
    "Seu vocabulário é limitado, falta diversidade",
    "Suas rimas são superficiais, não têm profundidade",
    "Sua cadência é irregular, falta fluidez",
    "Seu estilo é tão ultrapassado, parece que está preso nos anos 90",
    "Seu visual é tão brega, parece que saiu de uma festa à fantasia",
    "Seu jeito de dançar é tão desengonçado, parece que está pisando em ovos",
    "Seu gosto musical é tão duvidoso, parece que vive numa estação de rádio antiga",
    "Seu senso de moda é tão questionável, parece que se vestiu no escuro",
    "Seu vocabulário é tão limitado, parece que só conhece palavras de criança",
    "Sua presença é tão sem graça, parece que passa despercebido em qualquer lugar",
    "Seu corte de cabelo é tão cafona, parece que parou no tempo",
    "Sua capacidade de socializar é tão fraca, parece que não sabe se relacionar com pessoas de verdade",
    "Seu humor é tão sem graça, parece que faz as pessoas dormirem de tédio",
    "Sua personalidade é tão sem sal, parece que não tem nenhum tempero na vida",
    "Seu jeito de falar é tão enrolado, parece que está engolindo as palavras",
    "Sua capacidade intelectual é tão limitada, parece que seu cérebro está em modo econômico",
    "Seu talento artístico é tão inexistente, parece que nem uma criança de cinco anos faria pior",
    "Sua habilidade esportiva é tão fraca, parece que nasceu com dois pés esquerdos",
    "Seu senso de direção é tão ruim, parece que se perde até dentro de casa",
    "Sua memória é tão fraca, parece que esquece as coisas antes mesmo de aprender",
    "Seu jeito de cozinhar é tão desastroso, parece que transforma qualquer prato em um desastre culinário",
    "Sua capacidade de concentração é tão baixa, parece que tem déficit de atenção crônico",
    "Seu senso de humor é tão sem graça, parece que faz os palhaços chorarem de tristeza",
    "Sua criatividade é tão limitada, parece que só sabe copiar e colar",
    "Seu talento musical é tão inexistente, parece que é uma tortura para os ouvidos",
    "Sua capacidade de liderança é tão fraca, parece que não consegue nem liderar um formigueiro",
    "Seu jeito de se vestir é tão fora de moda, parece que vive numa cápsula do tempo",
    "Sua habilidade em resolver problemas é tão nula, parece que precisa de um manual para abrir uma porta",
    "Seu conhecimento geral é tão limitado, parece que nunca saiu da primeira série",
    "Sua capacidade de tomar decisões é tão fraca, parece que fica paralisado como um cervo nos faróis de um carro",
    "Seu talento para a dança é tão inexistente, parece que está pisando em ovos numa pista de gelo",
    "Sua habilidade em lidar com finanças é tão fraca, parece que gasta dinheiro como água sem pensar nas consequências",
    "Seu talento é tão grande quanto uma formiga em um desfile de elefantes.",
    "Sua inteligência é tão afiada quanto uma colher de plástico.",
    "Seu estilo é tão fashion quanto uma meia com sandálias.",
    "Sua coragem é tão admirável quanto a de uma borboleta em um furacão.",
    "Sua habilidade esportiva é tão impressionante quanto a de um caracol em uma maratona.",
    "Seu senso de humor é tão afiado quanto uma bola de algodão.",
    "Sua presença é tão marcante quanto uma pegada na areia.",
    "Sua voz é tão melodiosa quanto um gato arranhando um quadro-negro.",
    "Seu carisma é tão magnético quanto um ímã sem força.",
    "Sua personalidade é tão cativante quanto um deserto sem areia.",
    "Seu charme é tão irresistível quanto uma porta giratória com defeito.",
    "Sua habilidade de concentração é tão impressionante quanto um peixe fora d'água.",
    "Seu talento musical é tão único quanto uma música desafinada.",
    "Sua capacidade de liderança é tão inspiradora quanto uma bússola quebrada.",
    "Seu carisma é tão envolvente quanto um livro em branco.",
    "Sua inteligência é tão brilhante quanto uma lâmpada queimada.",
    "Seu estilo é tão moderno quanto uma televisão de tubo.",
    "Sua habilidade de resolver problemas é tão eficiente quanto um guarda-chuva furado.",
    "Seu gosto musical é tão sofisticado quanto um alarme de carro.",
    "Sua memória é tão prodigiosa quanto um queijo suíço.",
    "Seu talento artístico é tão impressionante quanto uma pintura feita com os pés.",
    "Sua paciência é tão inabalável quanto uma folha ao vento.",
    "Seu carisma é tão contagiante quanto uma tosse em um elevador lotado.",
    "Sua criatividade é tão ilimitada quanto um saco vazio.",
    "Seu senso de moda é tão inovador quanto uma fantasia de palhaço.",
    "Sua habilidade culinária é tão refinada quanto um macarrão instantâneo.",
    "Seu talento esportivo é tão impressionante quanto uma corrida de tartarugas.",
    "Sua inteligência é tão aguçada quanto uma bola de praia.",
    "Seu charme é tão sedutor quanto uma porta giratória sem maçaneta.",
    "Sua personalidade é tão magnética quanto um ímã desmagnetizado.",
];