export const questionsEres: string[] = [
    "Por que o céu é azul se os pássaros são vermelhos?",
    "Quanto pesa uma nuvem feita de sorvete de caramelo?",
    "Onde os unicórnios guardam seus segredos mágicos?",
    "Qual é o sabor do vento em uma tarde de outono?",
    "Por que as abóboras dançam ao luar na noite de São João?",
    "Quem ensinou os gatos a tocar violão?",
    "Quantas estrelas cabem em um chapéu de melancia?",
    "Onde se esconde a risada do arco-íris quando ninguém está olhando?",
    "Quem escreveu as rimas do mar na concha encantada?",
    "Qual é o segredo que o espelho conta para a lua ao anoitecer?",
    "Por que os peixes voam quando a chuva vira gelatina?",
    "Como uma borboleta faz balé no topo de um lápis amarelo?",
    "O que as flores dizem quando as abelhas estão dormindo?",
    "Por que os girassóis correm atrás das borboletas no jardim?",
    "Qual é a cor da música que os passarinhos cantam?",
    "Onde estão os sinos que tocam quando as estrelas caem do céu?",
    "Quantos sorrisos cabem em uma xícara de algodão-doce?",
    "Por que as montanhas dançam quando a neve vira arco-íris?",
    "Qual é o segredo que o rio sussurra para as pedras?",
    "Como o vento faz malabarismos com os cabelos das nuvens?",
    "Por que as girafas sonham em escalar o arco-íris?",
    "O que os grilos conversam com as estrelas nas noites de verão?",
    "Quantos pulos dá um sapo para chegar à lua?",
    "Por que as formigas escrevem poesia nas folhas de outono?",
    "Qual é a receita para transformar sonhos em arco-íris?",
    "Onde se escondem as palavras que saltam dos livros encantados?",
    "Quem ensinou os peixes a nadar na poça de tinta colorida?",
    "Por que os espelhos têm tantos segredos nos sonhos das crianças?",
    "Como as estrelas se escondem quando a noite fica brincalhona?",
    "O que os gnomos fazem quando as fadas voam sobre os cogumelos?",
    "Por que as nuvens se transformam em doces na boca do sol?",
    "Qual é o cheiro do arco-íris quando chove doce de leite?",
    "Por que os patos usam guarda-chuvas em dias ensolarados?",
    "Onde os elefantes guardam as chaves de suas bicicletas invisíveis?",
    "Quem ensinou os girafas a andar de patins no gelo?",
    "Quantas voltas dá uma lesma em uma pista de corrida?",
    "Por que as árvores dançam quando ninguém está olhando?",
    "Como as estrelas fazem para brilhar mesmo durante o dia?",
    "O que os fantasmas conversam com as sombras da meia-noite?",
    "Por que as abelhas voam de trás para frente na primavera?",
    "Qual é o segredo que a lua sussurra para os morcegos na escuridão?",
    "Onde estão as pegadas do vento quando ele passa correndo?",
    "Quem ensinou os sapos a fazer acrobacias nos lírios do lago?",
    "Quantos pulos dá um canguru para alcançar a lua?",
    "Por que as estrelas se transformam em fadas nas noites de verão?",
    "Como os peixes sabem tocar guitarra debaixo d'água?",
    "O que as pedras contam para as ondas quando elas batem na praia?",
    "Por que os pássaros usam óculos escuros ao voar na tempestade?",
    "Qual é o sabor do vento quando passa por uma floresta de algodão?",
    "Onde estão os sorrisos das estrelas quando o céu está nublado?",
    "Quem ensinou os coelhos a fazerem malabarismos com cenouras?",
    "Quantas pegadas cabem em uma trilha invisível?",
    "Por que as borboletas pintam quadros com asas de arco-íris?",
    "Como as abelhas sabem dançar o tango com as flores no jardim?",
    "O que as nuvens dizem quando encontram uma montanha pelo caminho?",
    "Por que os gatos têm segredos escritos nas patas de trás?",
    "Qual é o destino das pegadas do tempo quando ele passa correndo?",
    "Onde estão as chaves do tesouro que o pirata esqueceu na ilha deserta?",
    "Quem ensinou as estrelas a desenharem constelações no céu?",
    "Quantas voltas dá uma borboleta em um carrossel de algodão-doce?",
    "Por que os grilos tocam violino em concertos de passarinhos?",
    "Como as árvores sabem as palavras das histórias que o vento sussurra?",
    "O que as sombras contam para a lua quando ela está cansada de brilhar?",
    "Se pudesse voar, para onde iria primeiro?",
    "Se pudesse ter um animal de estimação incomum, qual seria?",
    "Se pudesse viver em qualquer época histórica, qual escolheria?",
    "Se pudesse ter um superpoder relacionado à natureza, qual seria?",
    "Se pudesse criar uma nova lei, qual seria e por quê?",
    "Se pudesse ter um talento extraordinário, qual gostaria de ter?",
    "Se pudesse viajar para qualquer lugar do universo, para onde iria?",
    "Se pudesse mudar de profissão sem limitações, qual escolheria?",
    "Se pudesse ser um personagem de filme, quem seria e por quê?",
    "Se pudesse viver em um mundo fictício, qual escolheria?",
    "Se pudesse ter um encontro com qualquer pessoa histórica, quem seria?",
    "Se pudesse dominar uma forma de arte, qual escolheria?",
    "Se pudesse inventar um objeto revolucionário, o que seria?",
    "Se pudesse ser um elemento da natureza, qual seria?",
    "Se pudesse ter um jantar com três celebridades, quem convidaria?",
    "Se pudesse criar um novo feriado, qual seria e como seria celebrado?",
    "Se pudesse ser um personagem de livro, qual seria?",
    "Se pudesse ter um poder de cura, como o usaria?",
    "Se pudesse ter uma conversa com um animal, qual escolheria e o que perguntaria?",
    "Se pudesse remodelar sua cidade, o que mudaria?",
    "Se pudesse ter uma viagem no tempo de um dia, para onde voltaria?",
    "Se pudesse ser um herói ou vilão de história em quadrinhos, quem seria?",
    "Se pudesse ter um talento musical, qual instrumento gostaria de tocar?",
    "Se pudesse ser um objeto do cotidiano, qual seria?",
    "Se pudesse aprender instantaneamente qualquer língua, qual escolheria?",
    "Se pudesse ter uma habilidade sobre-humana, qual gostaria de ter?",
    "Se pudesse fazer uma pergunta a qualquer pessoa do passado, o que perguntaria?",
    "Se pudesse ter uma conversa com seu eu do futuro, o que diria?",
    "Se pudesse ter um encontro com um personagem de desenho animado, quem seria?",
    "Se pudesse criar um novo esporte, qual seria e como seria jogado?",
    "Se pudesse ter uma profissão dos sonhos, qual escolheria?"
];
  