export const themes: string[] = [
    "Espaço sideral",
    "Robótica",
    "Moda",
    "História antiga",
    "Viagens",
    "Esportes radicais",
    "Gastronomia",
    "Psicologia",
    "Artes marciais",
    "Sustentabilidade",
    "Tecnologia",
    "Filosofia",
    "Animais selvagens",
    "Música",
    "Arquitetura",
    "Literatura",
    "Fotografia",
    "Cinema",
    "Ciência",
    "História da arte",
    "Ecologia",
    "Medicina",
    "Mitologia",
    "Dança",
    "Política",
    "Desenho animado",
    "Religião",
    "Jardinagem",
    "História do Brasil",
    "Astrologia",
    "Design de interiores",
    "Jogos de tabuleiro",
    "Culinária internacional",
    "Antropologia",
    "Engenharia",
    "Ficção científica",
    "Pintura",
    "Esportes olímpicos",
    "Criptomoedas",
    "Comédia",
    "Meditação",
    "História medieval",
    "Música clássica",
    "Moda vintage",
    "Paleontologia",
    "Marketing",
    "Teatro",
    "Artesanato",
    "Psicologia positiva",
    "Biologia marinha",
    "Artes circenses",
    "Fotografia de natureza",
    "Arte urbana",
    "Economia",
    "Literatura clássica",
    "Escultura",
    "Filosofia oriental",
    "História da moda",
    "Arqueologia",
    "Esportes de inverno",
    "Gastronomia regional",
    "Neurociência",
    "Poesia",
    "Botânica",
    "Moda sustentável",
    "Astrofísica",
    "Geografia",
    "Filmes de terror",
    "Pintura abstrata",
    "Design gráfico",
    "Sociologia",
    "Fotografia de retratos",
    "História da música",
    "Jardinagem urbana",
    "História da medicina",
    "Psicologia infantil",
    "Mitologia grega",
    "Dança contemporânea",
    "Relações internacionais",
    "Arquitetura moderna",
    "História da aviação",
    "Arte digital",
    "História do cinema",
    "Ciência forense",
    "Literatura de ficção",
    "Escrita criativa",
    "Ecoturismo",
    "Medicina alternativa",
    "História da fotografia",
    "Artes plásticas",
    "Cultura pop",
    "Fotografia de moda",
    "Marketing digital",
    "Teatro musical",
    "Artesanato em madeira",
    "Psicologia esportiva",
    "Biologia molecular",
    "Artes visuais",
    "Fotografia de casamento",
    "História da arte africana",
    "Gastronomia molecular",
    "Pintura renascentista",
    "Arte aborígene",
];